name: publish-master

on:
  push:
    branches: [ master ]

jobs:
  build:

    name: publish-master
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.101
        # Authenticates packages to push to GPR
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: '%NUGET_AUTH_TOKEN%'
    
    - name: Install dependencies
      run: dotnet restore
      env:
        NUGET_AUTH_TOKEN: ${{ github.token }}
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Install templates
      run: dotnet new install ./src/content/NewTemplate

    - name: Create folder for test projects
      run: mkdir tmp && mkdir tmp/TestProject

    - name: Create project from template
      run: |
        dotnet new sln
        dotnet new web-extended
        dotnet build
      working-directory: tmp/TestProject

    - name: Test
      run: dotnet test --no-restore --verbosity normal
      
    - name: Pack
      run: dotnet pack --no-build --configuration Release
      
    - name: PushNuget
      run: dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.PUBLISH_TO_NUGET_ORG }} --skip-duplicate
      
    - name: PushGithub
      run: dotnet nuget push "**/*.nupkg" --no-symbols --skip-duplicate
      env:
        NUGET_AUTH_TOKEN: ${{ github.token }}
